### ISSUE TITLE
Enhancement: Add Pagination

### ISSUE THREAD

**Issue by Soyvor** [rashen33/movie-app-react#7] opened 2023-10-01 14:26 UTC
Description: Implement pagination for the movie list to improve user experience when there are many movies to display.
Difficulty: Easy
Labels: enhancement, frontend

**Comment by rashen33** [comment] 2023-10-01 23:34
If you are willing to resolve this issue l can assign you.

**Comment by lunoos** [comment] 2023-10-02 10:36
Hi @rashen33 i am willing to work on the issue can u please assign it to me.

**Comment by rashen33** [comment] 2023-10-02 10:40
Hey @Soyvor. You can work on this. I will assign you.

**Comment by lunoos** [comment] 2023-10-02 15:29
Hey i tried setting up the project but page is not getting loaded. It seams like the API that your using is not returning anything.

**Comment by codewithinfiver** [comment] 2023-10-10 16:43
Hey @rashen33, I would like to work on this if you reassign!

**Comment by rashen33** [comment] 2023-10-11 10:48
Hey @codewithinfiver the issue is currently colosed.

**Closed** 2023-10-11 10:48 UTC
Labels: enhancement, hacktoberfest
